name: battery_details
description: A new Flutter plugin project.
version: 1.0.1
homepage: https://github.com/ravitaak/battery_details.git

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.codedrink.battery_details
        pluginClass: BatteryDetailsPlugin

